ci:
  skip: [pylint]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: (appinfo|img|l10n|lib|src)
    -   id: trailing-whitespace
        exclude: (appinfo|img|l10n|lib|src)
    -   id: check-toml
    -   id: mixed-line-ending

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        types: [file, python]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
     -  id: mypy
        files: main.py
        additional_dependencies: [types-requests]

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint "main.py"
        language: system
        types: [ python ]
        pass_filenames: false
        args:
            [
                "-rn", # Only display messages
                "-sn", # Don't display the score
            ]
