[tool.black]
line-length = 120
target-versions = ["py39"]
preview = true

[tool.isort]
profile = "black"

[tool.pylint]
master.py-version = "3.9"
design.max-attributes = 8
design.max-branches = 14
design.max-locals = 16
design.max-returns = 8
basic.good-names = [
    "a", "b", "c", "d", "e", "f", "i", "j", "k", "v", "t",
    "ex", "_", "fp", "im",
]
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
messages_control.disable = [
    "missing-class-docstring",
    "missing-function-docstring",
    "line-too-long",
]

[tool.mypy]
ignore_missing_imports = true
warn_no_return = true
strict_optional = true
